name: Build and Deploy catalogue microservice to Development

on:
  push:
    branches-ognore:
      - 'main'   

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/microservices-nodejs.yaml@main
    with:
      MICROSERVICE: catalogue
      IMAGE: catalogue
      NAMESPACE: catalogue-microservice
      RELEASE: catalogue
      WORKING_DIR: ./catalogue
      DOCKERFILE_PATH: ./catalogue
    secrets: inherit